spring:
  profiles:
    active: @spring.profiles.active@
  management:
    endpoints:
      web:
        exposure:
          include: health, info, env
    endpoint:
      health:
        show-details: always
